name: madura_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

#-------------------- PACKAGE --------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.3.0
  intl: ^0.18.0
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.3
  smooth_page_indicator: ^1.2.0+3
  change_app_package_name: ^1.4.0
  shared_preferences: ^2.5.1
  firebase_storage: ^12.4.2

  lottie: ^3.2.0
  connectivity_plus: ^6.1.1

  # Icon
  iconsax: ^0.0.8
  iconsax_plus: ^1.0.0
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_app_check: ^0.3.2+1
  google_sign_in: ^6.2.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  supabase_flutter: ^2.8.3
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0
  flutter_dotenv: ^5.2.1
  file_picker: ^8.3.3
  firebase_database: ^11.3.2
  webview_flutter: ^4.10.0
  midtrans_snap: ^1.0.0
  toolkit: ^0.3.2

  #-------------------- PACKAGE END --------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  #-------------------- LOCAL ASSETS --------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/content/
    - .env

  #-------------------- LOCAL FONT --------------------#
  fonts:
    - family: Poppins
      fonts:
        # - asset: assets/fonts/Poppins-Light.ttf
        #   weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        # - asset: assets/fonts/Poppins-Italic.ttf
        #   style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        # - asset: assets/fonts/Poppins-MediumItalic.ttf
        #   weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
